const tags = [
    "Aerospace",
    "Aerospace Engineering",
    "All Grades",
    "Architecture",
    "Art",
    "Art/Design",
    "Astronomy",
    "Biology",
    "Business",
    "Chemistry",
    "Community Service",
    "Competition",
    "Computer Science",
    "Cybersecurity",
    "Debate",
    "Economics",
    "Electrical Engineering",
    "Engineering",
    "Entrepreneurship",
    "Environment",
    "Environmental Science",
    "Film",
    "Foreign Language",
    "Freshman",
    "General",
    "Geography",
    "Global Affairs",
    "Government/Politics",
    "History",
    "In-Person",
    "In-Person. All Grades",
    "In-person",
    "Internship",
    "Junior",
    "Juniors",
    "Law",
    "Leadership",
    "Math",
    "Mathematics",
    "Mechanical Engineering",
    "Medicine",
    "Music",
    "Neuroscience",
    "Performing Arts",
    "Photography",
    "Physics",
    "Psychology",
    "Research",
    "Research. Summer Program",
    "Robotics",
    "STEM",
    "Senior",
    "Seniors",
    "Sophomore",
    "Stem",
    "Summer Program",
    "Summer Programs",
    "Virtual",
    "Writing",
];
export default tags;
